language: generic
sudo: required
services: 
  - docker
  
before_install:
  - docker build -t andreyguevara/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true andreyguevara/docker-react npm run test